import 'dart:convert';
import 'package:drift/drift.dart';
import '../database.dart';

/// ~40 alimenti dal protocollo nutrizionale verificato (EN/ZH/RU, 80+ fonti).
/// Macro values da USDA FoodData Central cross-checked.
final foodSeedData = <FoodItemsCompanion>[
  // ── Tier 1: Ringiovanimento multi-meccanismo (consumo quotidiano) ──
  _food('Germogli di broccoli', 'Tier 1 — Ringiovanimento', 4.0, 4.0, 0.6, 35, 2.6, null,
    '30g (11kcal)', 'Aggiunti a insalate, panini, smoothie',
    'Sulforafano 10-100× più potente dei broccoli maturi. Attiva Nrf2, autofagia, senolitico',
    {'sulforaphane_mg': 40, 'mechanisms': ['autophagy', 'NAD+', 'senolytic', 'telomeres', 'mitochondria', 'stem_cells']},
    1, 'Pasto 1'),
  _food('Tè verde (foglie)', 'Tier 1 — Ringiovanimento', 0.0, 0.0, 0.0, 1, null, null,
    '200ml infuso', 'Bevanda con pasti, freddo d\'estate',
    'EGCG: inibitore mTOR, attivatore autofagia, senolitico',
    {'EGCG_mg': 50, 'mechanisms': ['autophagy', 'senolytic', 'telomeres', 'mitochondria', 'stem_cells']},
    1, 'Pasto 1'),
  _food('Fragole', 'Tier 1 — Ringiovanimento', 0.7, 7.7, 0.3, 32, 2.0, 40,
    '150g (48kcal)', 'Fresche, nello yogurt, nel porridge',
    'Fonte #1 fisetina + ellagitannine (precursore urolitina A)',
    {'fisetin_ug_per_g': 160, 'mechanisms': ['senolytic', 'telomeres', 'mitochondria', 'stem_cells']},
    1, null),
  _food('Melagrana', 'Tier 1 — Ringiovanimento', 1.7, 18.7, 1.2, 83, 4.0, 35,
    '100g semi (83kcal)', 'Semi come snack, nel porridge, insalata',
    'Fonte primaria precursori urolitina A per mitofagia',
    {'ellagitannins': true, 'mechanisms': ['mitochondria', 'stem_cells', 'autophagy', 'telomeres']},
    1, null),
  _food('Noci', 'Tier 1 — Ringiovanimento', 15.2, 13.7, 65.2, 654, 6.7, 15,
    '20g (131kcal)', 'Snack, nel porridge, nelle insalate',
    'Ellagitannine (urolitina A) + omega-3 ALA + protezione telomeri',
    {'omega3_ALA_g': 9.1, 'mechanisms': ['mitochondria', 'telomeres', 'senolytic', 'stem_cells']},
    1, 'Pasto 1'),
  _food('Salmone', 'Tier 1 — Ringiovanimento', 20.4, 0.0, 13.4, 208, 0.0, null,
    '150g (312kcal)', 'Grigliato, al forno, crudo (sashimi)',
    'Omega-3 DHA/EPA, niacina — protezione telomeri e mitocondri',
    {'omega3_EPA_DHA_g': 2.3, 'niacin_mg': 8, 'mechanisms': ['NAD+', 'telomeres', 'mitochondria', 'stem_cells']},
    1, 'Pasto 2'),
  _food('Sgombro', 'Tier 1 — Ringiovanimento', 18.6, 0.0, 13.9, 205, 0.0, null,
    '150g (308kcal)', 'Grigliato, al forno',
    'Come salmone: omega-3, niacina. Più economico',
    {'omega3_EPA_DHA_g': 2.7, 'mechanisms': ['NAD+', 'telomeres', 'mitochondria']},
    1, 'Pasto 2'),

  // ── Tier 2: Forte meccanismo singolo (3-5×/settimana) ──
  _food('Germe di grano', 'Tier 2 — Meccanismo forte', 23.2, 51.8, 9.7, 360, 13.2, null,
    '15g (54kcal)', 'Nel porridge, nello yogurt, nei frullati',
    'Fonte #1 spermidina al mondo (24-35mg/100g) — attivatore autofagia',
    {'spermidine_mg': 30, 'mechanisms': ['autophagy']},
    2, 'Pasto 1'),
  _food('Mirtilli', 'Tier 2 — Meccanismo forte', 0.7, 14.5, 0.3, 57, 2.4, 53,
    '100g (57kcal)', 'Freschi, nel porridge, smoothie',
    'Antociani: protezione telomeri, staminali, mitocondri',
    {'anthocyanins_mg': 163, 'mechanisms': ['telomeres', 'stem_cells', 'mitochondria', 'senolytic']},
    2, 'Pasto 1'),
  _food('Spinaci', 'Tier 2 — Meccanismo forte', 2.9, 3.6, 0.4, 23, 2.2, 15,
    '80g crudi (18kcal)', 'Insalata, cotti, smoothie',
    'Folato, quercetina — telomeri e NAD+',
    {'folate_mcg': 194, 'quercetin_mg': 4, 'mechanisms': ['telomeres', 'NAD+', 'senolytic']},
    2, null),
  _food('Cipolla rossa', 'Tier 2 — Meccanismo forte', 1.1, 9.3, 0.1, 40, 1.7, 10,
    '50g (20kcal)', 'Cruda in insalata, cotta nei piatti',
    'Quercetina + fisetina — senolitico',
    {'quercetin_mg': 20, 'mechanisms': ['senolytic']},
    2, 'Pasto 2'),
  _food('Edamame', 'Tier 2 — Meccanismo forte', 11.9, 8.6, 5.2, 122, 5.2, 15,
    '80g (98kcal)', 'Snack, nei bowl, insalate',
    'Spermidina (20.7mg/100g) + NMN + genisteina',
    {'spermidine_mg': 21, 'mechanisms': ['autophagy', 'NAD+']},
    2, 'Pasto 3'),
  _food('Funghi shiitake', 'Tier 2 — Meccanismo forte', 2.2, 6.8, 0.5, 34, 2.5, null,
    '80g (27kcal)', 'Saltati, in zuppe, con riso',
    'Spermidina + ergotioneina + niacina',
    {'ergothioneine_mg': 13, 'mechanisms': ['autophagy', 'NAD+']},
    2, null),

  // ── Tier 3: Supporto longevità (consumo regolare) ──
  _food('Capperi', 'Tier 3 — Supporto', 2.4, 4.9, 0.9, 23, 3.2, null,
    '10g (2kcal)', 'Condimento per insalate, pesce, pasta',
    'Fonte #1 quercetina al mondo (234-365mg/100g)',
    {'quercetin_mg': 300, 'mechanisms': ['senolytic']},
    3, null),
  _food('Olio EVO', 'Tier 3 — Supporto', 0.0, 0.0, 100.0, 884, 0.0, null,
    '10g (88kcal)', 'Condimento crudo, cottura a bassa T',
    'Attivazione AMPK, polifenoli, oleocantale',
    {'polyphenols': true, 'mechanisms': ['AMPK']},
    3, null),
  _food('Avocado', 'Tier 3 — Supporto', 2.0, 8.5, 14.7, 160, 6.7, 15,
    '50g (80kcal)', 'Toast, insalata, smoothie',
    'Fonte NMN, grassi mono-insaturi',
    {'NMN': true, 'mechanisms': ['NAD+']},
    3, 'Pasto 3'),
  _food('Cioccolato fondente 99%', 'Tier 3 — Supporto', 14.3, 24.0, 55.0, 598, 11.0, 20,
    '10g (60kcal)', 'Dopo cena, come snack',
    'Flavanoli: protezione vascolare (NON per FGF21)',
    {'flavanols_mg': 100, 'mechanisms': ['vascular']},
    3, 'Pasto 3'),
  _food('Mandorle', 'Tier 3 — Supporto', 21.2, 21.7, 49.9, 579, 12.5, 15,
    '20g (116kcal)', 'Snack, nel porridge',
    'Ellagitannine (precursore urolitina A)',
    {'mechanisms': ['mitochondria']},
    3, null),
  _food('Lamponi', 'Tier 3 — Supporto', 1.2, 11.9, 0.7, 52, 6.5, 32,
    '100g (52kcal)', 'Freschi, nel porridge, smoothie',
    'Ellagitannine + fisetina',
    {'fisetin_ug_per_g': 5, 'mechanisms': ['senolytic', 'mitochondria']},
    3, null),
  _food('Lenticchie', 'Tier 3 — Supporto', 9.0, 20.1, 0.4, 116, 7.9, 30,
    '150g cotte (174kcal)', 'Zuppa, insalata, contorno',
    'Spermidina + folati + proteine vegetali',
    {'spermidine_mg': 4, 'mechanisms': ['autophagy']},
    3, 'Pasto 3'),
  _food('Ceci', 'Tier 3 — Supporto', 8.9, 27.4, 2.6, 164, 7.6, 28,
    '150g cotti (246kcal)', 'Hummus, insalata, zuppa',
    'Spermidina + proteine vegetali',
    {'spermidine_mg': 3, 'mechanisms': ['autophagy']},
    3, null),
  _food('Asparagi', 'Tier 3 — Supporto', 2.2, 3.9, 0.1, 20, 2.1, 15,
    '150g (30kcal)', 'Grigliati, al vapore, nei bowl',
    'Spermidina, folati',
    {'spermidine_mg': 4, 'mechanisms': ['autophagy']},
    3, 'Pasto 3'),
  _food('Semi di lino', 'Tier 3 — Supporto', 18.3, 28.9, 42.2, 534, 27.3, null,
    '10g (53kcal)', 'Nel porridge, insalate, smoothie',
    'Omega-3 ALA per protezione telomeri',
    {'omega3_ALA_g': 22.8, 'mechanisms': ['telomeres']},
    3, 'Pasto 1'),

  // ── Tier 4: Neutri (macro, no longevity specifico) ──
  _food('Petto di pollo', 'Tier 4 — Neutro', 31.0, 0.0, 3.6, 165, 0.0, null,
    '150g (248kcal)', 'Grigliato, al forno, in insalata',
    'Proteine lean ad alto valore biologico',
    {'mechanisms': []},
    4, 'Pasto 2'),
  _food('Uova intere', 'Tier 4 — Neutro', 12.6, 0.7, 9.5, 143, 0.0, null,
    '2 uova 120g (172kcal)', 'Strapazzate, sode, in camicia',
    'Colina, niacina, proteine complete',
    {'choline_mg': 147, 'mechanisms': []},
    4, 'Pasto 1'),
  _food('Avena integrale', 'Tier 4 — Neutro', 16.9, 66.3, 6.9, 389, 10.6, 55,
    '50g (195kcal)', 'Porridge, overnight oats',
    'Beta-glucani per salute intestinale',
    {'beta_glucan_g': 4, 'mechanisms': []},
    4, 'Pasto 1'),
  _food('Riso integrale', 'Tier 4 — Neutro', 2.6, 23.0, 0.9, 111, 1.8, 50,
    '150g cotto (167kcal)', 'Contorno, bowl, sushi',
    'Fonte energia. Raffreddato = amido resistente tipo 3',
    {'resistant_starch': true, 'mechanisms': []},
    4, 'Pasto 2'),
  _food('Yogurt greco', 'Tier 4 — Neutro', 10.0, 3.6, 0.7, 59, 0.0, null,
    '150g (89kcal)', 'Colazione, con frutta, come snack',
    'Proteine + probiotici',
    {'mechanisms': []},
    4, 'Pasto 1'),
  _food('Broccoli', 'Tier 4 — Neutro', 2.8, 7.0, 0.4, 34, 2.6, 10,
    '200g (68kcal)', 'Al vapore, grigliati, in stir-fry',
    'Sulforafano (meno dei germogli), fibre',
    {'sulforaphane_mg': 1, 'mechanisms': []},
    4, 'Pasto 2'),
  _food('Patata dolce', 'Tier 4 — Neutro', 1.6, 20.1, 0.1, 86, 3.0, 63,
    '150g (129kcal)', 'Al forno, purè, in bowl',
    'Beta-carotene, fonte energia',
    {'mechanisms': []},
    4, null),
  _food('Tacchino', 'Tier 4 — Neutro', 29.0, 0.0, 1.0, 135, 0.0, null,
    '150g (203kcal)', 'Grigliato, al forno, affettato',
    'Proteine magre ad alto valore biologico',
    {'mechanisms': []},
    4, 'Pasto 2'),
];

FoodItemsCompanion _food(
  String name, String category,
  double protein, double carbs, double fats, double calories,
  double? fiber, int? gi,
  String portion, String ideas,
  String benefit, Map<String, dynamic> compounds,
  int tier, String? timing,
) {
  return FoodItemsCompanion.insert(
    name: name,
    category: category,
    proteinPer100g: protein,
    carbsPer100g: carbs,
    fatsPer100g: fats,
    caloriesPer100g: calories,
    fiberPer100g: Value(fiber),
    glycemicIndex: Value(gi),
    portionExample: portion,
    useIdeas: ideas,
    longevityBenefit: benefit,
    activeCompounds: jsonEncode(compounds),
    longevityTier: tier,
    idealTiming: Value(timing),
  );
}
